### ISSUE TITLE
Fix typing issues

### ISSUE THREAD

**Issue by LouisCAD** [ShikaSD/compose-server-side#1]
On mobile (tested on Chrome on Android 10), the typing in the todo section seems to trigger slow code on every typed character, which results in dropped characters and poor responsiveness.

I'd assume the same issue happens on non mobile devices.

**Comment by ShikaSD** [comment]
Hey, thanks for reporting that!
That's the annoying side of testing most stuff on the localhost 😅 
Input state is a bit annoying to handle, but I may have a trick that fixes that, will try to deploy it today.
