### ISSUE TITLE
aosp.location ?

### ISSUE THREAD

**Issue by CMingTseng** [ShikaSD/compose-server-side#3]
Dear Sir

i checkout this project 

open build.gradle file at compose-wrapper 

at buildscript  it write use   "aosp.location"   from local.properties !!

but   local.properties is myself !!  

where find aosp.location ?

THX

**Comment by ShikaSD** [comment]
Yeah, I used some sources from AOSP, which expected to be cloned separately.
I think this setup will be super annoying though as this repo is far behind the runtime, and is probably incompatible. You can check `deploy` branch instead which should have everything already precompiled.
