### ISSUE TITLE
1.4-M3 ?

### ISSUE THREAD

**Issue by CMingTseng** [ShikaSD/compose-server-side#4]
Dear Sir

so  now want use  Compose UI

we want use  special  version  compiler ?

org.jetbrains.kotlin:kotlin-compiler-embeddable:1.4.0-dev-withExperimentalGoogleExtensions-20200720

&

org.jetbrains.kotlin.plugin.serialization 1.4-M3 

can use  kotlin  stable  version   1.4.32 ?

THX

**Comment by ShikaSD** [comment]
Yeah, this version is not compatible with latest compiler, see comment in another thread for more explanation: https://github.com/ShikaSD/compose-server-side/issues/5#issuecomment-814842101
