### ISSUE TITLE
How replace  androidx.compose.Composable ?

### ISSUE THREAD

**Issue by CMingTseng** [ShikaSD/compose-server-side#6]
Dear Sir

i try to modify the project  use  Compose for Desktop, by JetBrains 

https://github.com/JetBrains/compose-jb

i look all  class

the KtorFeature  import androidx.compose.Composable 

the Composable  is from you modify jar file  at compose-wrapper/built 

but   Composable by HB  is  "androidx.compose.runTime.Composable

how to modify ?

THX

**Comment by ShikaSD** [comment]
I don't think it is compatible with modern compose, see comment in other thread:

https://github.com/ShikaSD/compose-server-side/issues/5#issuecomment-814842101
